name: Workflow solid-invention
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: |
          cat << EOF >> .env
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DEBUG=False
          DATABASE=test
          DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}
          DEFAULT_FROM_EMAIL=${{ secrets.DEFAULT_FROM_EMAIL }}
          DEFAULT_TO_EMAIL=${{ secrets.DEFAULT_TO_EMAIL }}
          EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
          POSTGRES_NAME=${{ secrets.POSTGRES_NAME }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASS=${{ secrets.POSTGRES_PASS }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          EOF
          python manage.py collectstatic --no-input
          coverage run --source='.' manage.py test
          coverage xml
      - name: Upload coverage to Codecov
        run: |
          pip install codecov
          codecov -t ${{ secrets.CODECOV_TOKEN }}
